version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: find-friend-pg
    environment:
      POSTGRES_DB: find-friend
      POSTGRES_USER: find-friend
      POSTGRES_PASSWORD: find-friend123
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
